export const SET_CUSTOMERS = "SET_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const ADD_ACCOUNT_TO_CUSTOMER = "ADD_ACCOUNT_TO_CUSTOMER";
export const DELETE_ACCOUNT_FROM_CUSTOMER = "DELETE_ACCOUNT_FROM_CUSTOMER";
export const SET_ACTIVE_CUSTOMER = "SET_ACTIVE_CUSTOMER";
